In [1]:
import pandas as pd
df=pd.read_csv('House-price.csv')
df.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  poor_prop airport  n_hos_beds  n_hot_rooms waterbody  rainfall  \
0      24.7       4.98     YES       5.480      11.1920     River        23   
1      22.2       9.14      NO       7.332      12.1728      Lake        42   
2      22.2       4.03      NO       7.394     101.1200      None        38   
3      21.3       2.94     YES       9.268      11.2672      Lake        45   
4      21.3       5.33      NO       8.824      11.2896      Lake        55   

  bus_ter     parks  Sold  
0     YES  0.049347     0  
1     YES  0.046146     1  
2     YES  0.045764     0  
3     YES  0.047151     0  
4     YES  0.039474     0

In [2]:
df=pd.get_dummies(df)
df.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  ...  rainfall     parks  Sold  airport_NO  airport_YES  \
0      24.7  ...        23  0.049347     0           0            1   
1      22.2  ...        42  0.046146     1           1            0   
2      22.2  ...        38  0.045764     0           1            0   
3      21.3  ...        45  0.047151     0           0            1   
4      21.3  ...        55  0.039474     0           1            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_None  waterbody_River  \
0               0                         0               0                1   
1               1                         0               0                0   
2               0                         0               1                0   
3               1                         0               0                0   
4               1                         0               0                0   

   bus_ter_YES  
0            1  
1            1  
2            1  
3            1  
4            1  

[5 rows x 23 columns]

In [3]:
del df['airport_NO']
del df['waterbody_None']
df.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  ...  n_hos_beds  n_hot_rooms  rainfall     parks  Sold  \
0      24.7  ...       5.480      11.1920        23  0.049347     0   
1      22.2  ...       7.332      12.1728        42  0.046146     1   
2      22.2  ...       7.394     101.1200        38  0.045764     0   
3      21.3  ...       9.268      11.2672        45  0.047151     0   
4      21.3  ...       8.824      11.2896        55  0.039474     0   

   airport_YES  waterbody_Lake  waterbody_Lake and River  waterbody_River  \
0            1               0                         0                1   
1            0               1                         0                0   
2            0               0                         0                0   
3            1               1                         0                0   
4            0               1                         0                0   

   bus_ter_YES  
0            1  
1            1  
2            1  
3            1  
4            1  

[5 rows x 21 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   price                     506 non-null    float64
 1   resid_area                506 non-null    float64
 2   air_qual                  506 non-null    float64
 3   room_num                  506 non-null    float64
 4   age                       506 non-null    float64
 5   dist1                     506 non-null    float64
 6   dist2                     506 non-null    float64
 7   dist3                     506 non-null    float64
 8   dist4                     506 non-null    float64
 9   teachers                  506 non-null    float64
 10  poor_prop                 506 non-null    float64
 11  n_hos_beds                506 non-null    float64
 12  n_hot_rooms               506 non-null    float64
 13  rainfall                  506 non-null    int64  
 14  parks     

In [11]:
df.n_hos_beds=df.n_hos_beds.fillna(df.n_hos_beds.mean())

In [5]:
import seaborn as sns
import numpy as np

In [19]:
x=df[['price']]
y=df['Sold']
x.head()

price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [14]:
y.head()


0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [15]:
#Logistic Regression from sklearn
from sklearn.linear_model import LogisticRegression
lgr=LogisticRegression()
lgr.fit(x,y)
print(lgr.intercept_,lgr.coef_)

[0.61477516] [[-0.03571865]]


In [16]:
#logistic regression from statmodels
import statsmodels.api as sn
import statsmodels.discrete.discrete_model as snm
x1=sn.add_constant(x)
logit=sn.Logit(y,x1).fit()
logit.summary()

Optimization terminated successfully.
         Current function value: 0.676690
         Iterations 5


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Thu, 09 Jun 2022   Pseudo R-squ.:                 0.01788
Time:                        00:45:45   Log-Likelihood:                -342.41
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 0.0004142
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6149      0.248      2.484      0.013       0.130       1.100
price         -0.0357      0.010     -3.417      0.001      -0.056      -0.015
==============================================================================
"""

In [17]:
#Logostic regression with multiple predictors
x_mul=df.loc[:,df.columns!='Sold']
y_mul=df['Sold']
lmr1=LogisticRegression()
lmr1.fit(x_mul,y_mul)
print(lmr1.coef_,lmr1.intercept_)

[[-0.25105402 -0.01968009 -0.25074689  0.93669182 -0.00642619  0.19845605
  -0.16980998  0.10268009 -0.4772184   0.22317515 -0.21151563  0.15813303
  -0.08365656 -0.00567704 -0.012443   -0.19652079 -0.01461654 -0.00327367
   0.13810098 -0.01246512]] [-0.00881151]


c:\Users\ADITYA SANDILYA\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [21]:
lmr1.predict_proba(x_mul)

array([[1.35398703e-01, 8.64601297e-01],
       [3.94561300e-01, 6.05438700e-01],
       [9.99759181e-01, 2.40818808e-04],
       ...,
       [2.53293242e-01, 7.46706758e-01],
       [2.84105854e-01, 7.15894146e-01],
       [1.76294960e-01, 8.23705040e-01]])

In [22]:
y_pred=lmr1.predict(x_mul)
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,

In [23]:
y_pred3=(lmr1.predict_proba(x_mul)[:,1]>=0.3).astype(bool)
from sklearn.metrics import confusion_matrix
confusion_matrix(y,y_pred)

array([[199,  77],
       [ 77, 153]], dtype=int64)

In [24]:
confusion_matrix(y,y_pred3)

array([[118, 158],
       [ 16, 214]], dtype=int64)

In [28]:
from sklearn.metrics import recall_score,precision_score,roc_auc_score
precision_score(y,y_pred)


0.6652173913043479

In [26]:
recall_score(y,y_pred)

0.6652173913043479

In [29]:
roc_auc_score(y,y_pred)

0.6931159420289855

In [30]:
#Linear Discriminant Analysis
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda=LinearDiscriminantAnalysis()
lda.fit(x_mul,y)
y_pred_lda=lda.predict(x_mul)
confusion_matrix(y,y_pred_lda)

array([[201,  75],
       [ 76, 154]], dtype=int64)

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_mul,y,test_size=0.2,random_state=0)
print(x_train.shape,x_test.shape)

(404, 20) (102, 20)


In [33]:
lgr_t=LogisticRegression()
lgr_t.fit(x_mul,y)
y_test_pred=lgr_t.predict(x_test)
y_test_pred

c:\Users\ADITYA SANDILYA\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1], dtype=int64)

In [35]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_test_pred)

0.7156862745098039

In [36]:
confusion_matrix(y_test,y_test_pred)

array([[40, 18],
       [11, 33]], dtype=int64)

In [37]:
from sklearn import preprocessing
scaler=preprocessing.StandardScaler().fit(x_train)
x_train_s=scaler.transform(x_train)

In [38]:
scaler=preprocessing.StandardScaler().fit(x_test)
x_test_s=scaler.transform(x_test)

In [39]:
from sklearn.neighbors import KNeighborsClassifier
knn1=KNeighborsClassifier(n_neighbors=1)
knn1.fit(x_train_s,y_train)

KNeighborsClassifier(n_neighbors=1)

In [40]:
confusion_matrix(y_test,knn1.predict(x_test_s))

array([[32, 26],
       [21, 23]], dtype=int64)

In [41]:
accuracy_score(y_test,knn1.predict(x_test_s))

0.5392156862745098

In [49]:
knn2=KNeighborsClassifier(n_neighbors=3)
knn2.fit(x_train_s,y_train)
confusion_matrix(y_test,knn2.predict(x_test_s))

array([[34, 24],
       [22, 22]], dtype=int64)

In [61]:
from sklearn.model_selection import GridSearchCV
params={'n_neighbors' :[1,2,3,4,5,6,7,8,9,10]}
grid_search=GridSearchCV(KNeighborsClassifier(),params)
grid_search.fit(x_train_s,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [62]:
grid_search.best_params_
best_grid=grid_search.best_estimator_
y_test_pred1=best_grid.predict(x_test_s)

In [63]:
confusion_matrix(y_test,y_test_pred1)

array([[32, 26],
       [21, 23]], dtype=int64)